import "./globals.css";
import { ThemeProvider } from 'next-themes';

import { Navbar, Footer } from '@/components/index'
import Script from "next/script";
import { NFTProvider } from "@/context/NFTContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <NFTProvider>
      <ThemeProvider attribute="class">
        <body className="antialiased">
          <div className="dark:bg-nft-dark bg-white min-h-screen">
            <Navbar />
              {children}
            <Footer />
          </div>
          <Script 
            src="https://kit.fontawesome.com/1fd1b32f80.js" 
            crossOrigin="anonymous"
          />
        </body>
        </ThemeProvider>
        </NFTProvider>
    </html>
  );
}
